In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame([[8, 8, 4], [7, 9, 5], [6, 10, 6], [5, 12, 7]], columns=['CGPA', 'profile_score', 'LPA'])

In [3]:
df

CGPA  profile_score  LPA
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [4]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [5]:
model = Sequential()

In [6]:
model.add(Dense(2, activation='linear', input_dim = 2))
model.add(Dense(1, activation='linear'))

C:\Users\Admin-\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [7]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [8]:
model.get_weights()

[array([[-1.1156275 , -0.07919526],
        [ 0.9219302 , -0.41415393]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.18841493],
        [-1.3655933 ]], dtype=float32),
 array([0.], dtype=float32)]

In [12]:
optimizer = keras.optimizers.Adam(learning_rate=0.01)
model.compile(loss='mean_squared_error', optimizer=optimizer)

In [13]:
model.fit(df.iloc[:, 0:-1].values, df['LPA'].values, epochs=75, verbose=1, batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.2452 
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0986
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0576
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0467
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0456
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0377    
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0752
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0260
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0443
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0364
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0227
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0608
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0610
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0342
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0268
Epoch 16/75
4/4 ━━━━━━━━━━━━━

In [14]:
model.get_weights()

[array([[-1.1007538 ,  0.01271201],
        [ 0.89325285, -0.41663998]], dtype=float32),
 array([0.03318306, 0.00885477], dtype=float32),
 array([[ 0.09575023],
        [-1.3489147 ]], dtype=float32),
 array([-0.00616006], dtype=float32)]